### ISSUE TITLE
Make commit messages clearer in some instances

### ISSUE THREAD

**Issue by Cleop** [FAC10/week1-ajoy-facx-machine#82]
The commit message 'fix contact button' here isn't very descriptive/accurate. It's hard for me to understand what you've done without looking at the code and the code doesn't seem to reflect the change. It looks more like you've added a new id to the contact section. I'm not sure if I'm interpreting this incorrectly given what your code may have looked like at the time. But make sure your commit messages are a bit more detailed. So if it is a fix, say what kind, ie. Fixes typo or removes extra comma or adds extra parameter fixing bug.

<img width="1101" alt="screen shot 2017-02-24 at 10 36 01" src="https://cloud.githubusercontent.com/assets/16775804/23300374/22584a08-fa7d-11e6-872e-107aee842207.png">

**Comment by yvonne-liu** [comment]
Thanks! I totally overlooked that. I fixed the issue where the contact button wasn't linking to the contact section because it didn't have the proper `id` tag -- next time I will write a clearer commit messages because I even forgot myself when looking at this issue what the issue was! 😄
