### ISSUE TITLE
Two entries for the same class in css

### ISSUE THREAD

**Issue by Cleop** [FAC10/week1-ajoy-facx-machine#86]
You've listed the navbar__brand class twice in your css file.

```
.navbar__brand {
  font-size: 1.75em;
  font-family: monospace;
}

.navbar__brand {
  font-family: 'Exo',cursive;
}
```
https://github.com/FAC10/week1-ajoy-facx-machine/blob/master/style.css#L89-L96

**Comment by akinsho** [comment]
Thanks for spotting that i've remove the redundant conflicting class.
