### ISSUE TITLE
Repeat css font family

### ISSUE THREAD

**Issue by Cleop** [FAC10/week1-ajoy-facx-machine#89]
Two Helveticas?

```
body {
  font-family: 'Helvetica', Helvetica, Arial, sans-serif;
  color: #333333;
}
```

https://github.com/FAC10/week1-ajoy-facx-machine/blob/master/style.css#L32

**Comment by oliverjam** [comment]
I think this was meant to be `"Helvetica Neue", Helvetica, Arial, sans-serif;` but the 'Neue' got lost somewhere. This will be fixed by @Akin909 in a pull request soon to actually use the custom font we set.
